### PR TITLE
Code modernization: Use nullptr, fix QFlags(Zero) ctor deprecation warning

### PR DESCRIPTION
**Pull request by krf**

### CODE REVIEW

**Comment by krf** [comment]
Maybe also worthwhile pushing this to kdchart-2.7 branch, you decide.

**Comment by winterz** [comment]
this can go into the 3.0 release. cannot go into 2.7
master should be 2.8 at the moment.

**Comment by krf** [comment]
So, in other words, this can/should go to master?

**Comment by winterz** [comment]
no.  @ivan-cukic  is working on a pre-3.0 branch which also includes the Qt6 port.
I *think* this is the qt6-dev branch
perhaps we rename it to 3.0 or 3.0-dev

**Comment by krf** [comment]
Superseded by https://github.com/KDAB/KDChart/pull/21

**Pull request closed without merging**
